### ISSUE TITLE
Error 500 with Neos 3.3 LTS

### ISSUE THREAD

**Issue by mad99** [sitegeist/Sitegeist.MoveAlong#7]
Have an error 500 with misstyping uri's also after rm temporary and rescan:
 ```Argument 1 passed to Neos\Flow\Mvc\Routing\Router_Original::route() must be an instance of Neos\Flow\Mvc\Routing\Dto\RouteContext, instance of Neos\Flow\Http\Request given, called in pathTo/Data/Temporary/Development/Cache/Code/Flow_Object_Classes/Sitegeist_MoveAlong_Http_Component_MoveAlongRoutingComponent.php on line 62
Exception Code    0
Exception Type    TypeError
Thrown in File    Data/Temporary/Development/Cache/Code/Flow_Object_Classes/Neos_Flow_Mvc_Routing_Router.php
Line    101
Original File    Packages/Framework/Neos.Flow/Classes/Mvc/Routing/Router.php
```
Differences into line 101 Neos 3.2 <--> 3.3:
Neos 3.2 > public function route(Request $httpRequest)  (line 98)
Neos 3.3 > public function route(RouteContext $routeContext): array

Information from Martin Ficzel (Plguin-dev) on slack-channel:
Yeah, i fear we will habe to update moveAlong. No big deal but i have to find the time.

**Comment by mficzel** [comment]
This is fixed with release 3.0
